/**
 * account.newsbro.cc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import RepoAccountSrcApiDtoErrorResponse from './model/RepoAccountSrcApiDtoErrorResponse';
import RepoAccountSrcApiDtoLoginRequest from './model/RepoAccountSrcApiDtoLoginRequest';
import RepoAccountSrcApiDtoLoginResponse from './model/RepoAccountSrcApiDtoLoginResponse';
import RepoAccountSrcApiDtoRegisterRequest from './model/RepoAccountSrcApiDtoRegisterRequest';
import RepoAccountSrcApiDtoUserResponse from './model/RepoAccountSrcApiDtoUserResponse';
import AuthApi from './api/AuthApi';
import UserApi from './api/UserApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var AccountNewsbroCc = require('index'); // See note below*.
* var xxxSvc = new AccountNewsbroCc.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new AccountNewsbroCc.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new AccountNewsbroCc.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new AccountNewsbroCc.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.3.2
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The RepoAccountSrcApiDtoErrorResponse model constructor.
     * @property {module:model/RepoAccountSrcApiDtoErrorResponse}
     */
    RepoAccountSrcApiDtoErrorResponse,

    /**
     * The RepoAccountSrcApiDtoLoginRequest model constructor.
     * @property {module:model/RepoAccountSrcApiDtoLoginRequest}
     */
    RepoAccountSrcApiDtoLoginRequest,

    /**
     * The RepoAccountSrcApiDtoLoginResponse model constructor.
     * @property {module:model/RepoAccountSrcApiDtoLoginResponse}
     */
    RepoAccountSrcApiDtoLoginResponse,

    /**
     * The RepoAccountSrcApiDtoRegisterRequest model constructor.
     * @property {module:model/RepoAccountSrcApiDtoRegisterRequest}
     */
    RepoAccountSrcApiDtoRegisterRequest,

    /**
     * The RepoAccountSrcApiDtoUserResponse model constructor.
     * @property {module:model/RepoAccountSrcApiDtoUserResponse}
     */
    RepoAccountSrcApiDtoUserResponse,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
