/**
 * article.newsbro.cc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RepoArticleSrcApiDtoFeedbackRequest model module.
 * @module model/RepoArticleSrcApiDtoFeedbackRequest
 * @version 1.3.2
 */
class RepoArticleSrcApiDtoFeedbackRequest {
    /**
     * Constructs a new <code>RepoArticleSrcApiDtoFeedbackRequest</code>.
     * @alias module:model/RepoArticleSrcApiDtoFeedbackRequest
     */
    constructor() { 
        
        RepoArticleSrcApiDtoFeedbackRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RepoArticleSrcApiDtoFeedbackRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RepoArticleSrcApiDtoFeedbackRequest} obj Optional instance to populate.
     * @return {module:model/RepoArticleSrcApiDtoFeedbackRequest} The populated <code>RepoArticleSrcApiDtoFeedbackRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RepoArticleSrcApiDtoFeedbackRequest();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RepoArticleSrcApiDtoFeedbackRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RepoArticleSrcApiDtoFeedbackRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} value
 */
RepoArticleSrcApiDtoFeedbackRequest.prototype['value'] = undefined;






export default RepoArticleSrcApiDtoFeedbackRequest;

