/**
 * article.newsbro.cc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RepoArticleSrcApiDtoFeedbackResponse model module.
 * @module model/RepoArticleSrcApiDtoFeedbackResponse
 * @version 1.3.2
 */
class RepoArticleSrcApiDtoFeedbackResponse {
    /**
     * Constructs a new <code>RepoArticleSrcApiDtoFeedbackResponse</code>.
     * @alias module:model/RepoArticleSrcApiDtoFeedbackResponse
     */
    constructor() { 
        
        RepoArticleSrcApiDtoFeedbackResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RepoArticleSrcApiDtoFeedbackResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RepoArticleSrcApiDtoFeedbackResponse} obj Optional instance to populate.
     * @return {module:model/RepoArticleSrcApiDtoFeedbackResponse} The populated <code>RepoArticleSrcApiDtoFeedbackResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RepoArticleSrcApiDtoFeedbackResponse();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('news_id')) {
                obj['news_id'] = ApiClient.convertToType(data['news_id'], 'Number');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RepoArticleSrcApiDtoFeedbackResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RepoArticleSrcApiDtoFeedbackResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }

        return true;
    }


}



/**
 * @member {String} date
 */
RepoArticleSrcApiDtoFeedbackResponse.prototype['date'] = undefined;

/**
 * @member {Number} id
 */
RepoArticleSrcApiDtoFeedbackResponse.prototype['id'] = undefined;

/**
 * @member {Number} news_id
 */
RepoArticleSrcApiDtoFeedbackResponse.prototype['news_id'] = undefined;

/**
 * @member {Number} user_id
 */
RepoArticleSrcApiDtoFeedbackResponse.prototype['user_id'] = undefined;

/**
 * @member {Number} value
 */
RepoArticleSrcApiDtoFeedbackResponse.prototype['value'] = undefined;






export default RepoArticleSrcApiDtoFeedbackResponse;

