/**
 * Repo-Article
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RepoArticleSrcApiDtoRSSUpdateRequest model module.
 * @module model/RepoArticleSrcApiDtoRSSUpdateRequest
 * @version 1.0.0
 */
class RepoArticleSrcApiDtoRSSUpdateRequest {
    /**
     * Constructs a new <code>RepoArticleSrcApiDtoRSSUpdateRequest</code>.
     * @alias module:model/RepoArticleSrcApiDtoRSSUpdateRequest
     */
    constructor() { 
        
        RepoArticleSrcApiDtoRSSUpdateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RepoArticleSrcApiDtoRSSUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RepoArticleSrcApiDtoRSSUpdateRequest} obj Optional instance to populate.
     * @return {module:model/RepoArticleSrcApiDtoRSSUpdateRequest} The populated <code>RepoArticleSrcApiDtoRSSUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RepoArticleSrcApiDtoRSSUpdateRequest();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RepoArticleSrcApiDtoRSSUpdateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RepoArticleSrcApiDtoRSSUpdateRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['link'] && !(typeof data['link'] === 'string' || data['link'] instanceof String)) {
            throw new Error("Expected the field `link` to be a primitive type in the JSON string but got " + data['link']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['display_name'] && !(typeof data['display_name'] === 'string' || data['display_name'] instanceof String)) {
            throw new Error("Expected the field `display_name` to be a primitive type in the JSON string but got " + data['display_name']);
        }

        return true;
    }


}



/**
 * @member {String} description
 */
RepoArticleSrcApiDtoRSSUpdateRequest.prototype['description'] = undefined;

/**
 * @member {String} link
 */
RepoArticleSrcApiDtoRSSUpdateRequest.prototype['link'] = undefined;

/**
 * @member {String} name
 */
RepoArticleSrcApiDtoRSSUpdateRequest.prototype['name'] = undefined;


/**
 * @member {String} display_name
 */
RepoArticleSrcApiDtoRSSUpdateRequest.prototype['display_name'] = undefined;


export default RepoArticleSrcApiDtoRSSUpdateRequest;

