/**
 * article.newsbro.cc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RepoArticleSrcApiDtoFeedbackStatsResponse model module.
 * @module model/RepoArticleSrcApiDtoFeedbackStatsResponse
 * @version 1.3.2
 */
class RepoArticleSrcApiDtoFeedbackStatsResponse {
    /**
     * Constructs a new <code>RepoArticleSrcApiDtoFeedbackStatsResponse</code>.
     * @alias module:model/RepoArticleSrcApiDtoFeedbackStatsResponse
     */
    constructor() { 
        
        RepoArticleSrcApiDtoFeedbackStatsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RepoArticleSrcApiDtoFeedbackStatsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RepoArticleSrcApiDtoFeedbackStatsResponse} obj Optional instance to populate.
     * @return {module:model/RepoArticleSrcApiDtoFeedbackStatsResponse} The populated <code>RepoArticleSrcApiDtoFeedbackStatsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RepoArticleSrcApiDtoFeedbackStatsResponse();

            if (data.hasOwnProperty('article_title')) {
                obj['article_title'] = ApiClient.convertToType(data['article_title'], 'String');
            }
            if (data.hasOwnProperty('dislike_count')) {
                obj['dislike_count'] = ApiClient.convertToType(data['dislike_count'], 'Number');
            }
            if (data.hasOwnProperty('like_count')) {
                obj['like_count'] = ApiClient.convertToType(data['like_count'], 'Number');
            }
            if (data.hasOwnProperty('like_ratio')) {
                obj['like_ratio'] = ApiClient.convertToType(data['like_ratio'], 'Number');
            }
            if (data.hasOwnProperty('news_id')) {
                obj['news_id'] = ApiClient.convertToType(data['news_id'], 'Number');
            }
            if (data.hasOwnProperty('total_count')) {
                obj['total_count'] = ApiClient.convertToType(data['total_count'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RepoArticleSrcApiDtoFeedbackStatsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RepoArticleSrcApiDtoFeedbackStatsResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['article_title'] && !(typeof data['article_title'] === 'string' || data['article_title'] instanceof String)) {
            throw new Error("Expected the field `article_title` to be a primitive type in the JSON string but got " + data['article_title']);
        }

        return true;
    }


}



/**
 * @member {String} article_title
 */
RepoArticleSrcApiDtoFeedbackStatsResponse.prototype['article_title'] = undefined;

/**
 * @member {Number} dislike_count
 */
RepoArticleSrcApiDtoFeedbackStatsResponse.prototype['dislike_count'] = undefined;

/**
 * @member {Number} like_count
 */
RepoArticleSrcApiDtoFeedbackStatsResponse.prototype['like_count'] = undefined;

/**
 * @member {Number} like_ratio
 */
RepoArticleSrcApiDtoFeedbackStatsResponse.prototype['like_ratio'] = undefined;

/**
 * @member {Number} news_id
 */
RepoArticleSrcApiDtoFeedbackStatsResponse.prototype['news_id'] = undefined;

/**
 * @member {Number} total_count
 */
RepoArticleSrcApiDtoFeedbackStatsResponse.prototype['total_count'] = undefined;






export default RepoArticleSrcApiDtoFeedbackStatsResponse;

