/**
 * article.newsbro.cc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RepoArticleSrcApiDtoArticleUpdateRequest model module.
 * @module model/RepoArticleSrcApiDtoArticleUpdateRequest
 * @version 1.3.2
 */
class RepoArticleSrcApiDtoArticleUpdateRequest {
    /**
     * Constructs a new <code>RepoArticleSrcApiDtoArticleUpdateRequest</code>.
     * @alias module:model/RepoArticleSrcApiDtoArticleUpdateRequest
     * @param id {Number} 
     */
    constructor(id) { 
        
        RepoArticleSrcApiDtoArticleUpdateRequest.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>RepoArticleSrcApiDtoArticleUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RepoArticleSrcApiDtoArticleUpdateRequest} obj Optional instance to populate.
     * @return {module:model/RepoArticleSrcApiDtoArticleUpdateRequest} The populated <code>RepoArticleSrcApiDtoArticleUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RepoArticleSrcApiDtoArticleUpdateRequest();

            if (data.hasOwnProperty('abstract')) {
                obj['abstract'] = ApiClient.convertToType(data['abstract'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
            if (data.hasOwnProperty('subcategory')) {
                obj['subcategory'] = ApiClient.convertToType(data['subcategory'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RepoArticleSrcApiDtoArticleUpdateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RepoArticleSrcApiDtoArticleUpdateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RepoArticleSrcApiDtoArticleUpdateRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['abstract'] && !(typeof data['abstract'] === 'string' || data['abstract'] instanceof String)) {
            throw new Error("Expected the field `abstract` to be a primitive type in the JSON string but got " + data['abstract']);
        }
        // ensure the json data is a string
        if (data['category'] && !(typeof data['category'] === 'string' || data['category'] instanceof String)) {
            throw new Error("Expected the field `category` to be a primitive type in the JSON string but got " + data['category']);
        }
        // ensure the json data is a string
        if (data['link'] && !(typeof data['link'] === 'string' || data['link'] instanceof String)) {
            throw new Error("Expected the field `link` to be a primitive type in the JSON string but got " + data['link']);
        }
        // ensure the json data is a string
        if (data['subcategory'] && !(typeof data['subcategory'] === 'string' || data['subcategory'] instanceof String)) {
            throw new Error("Expected the field `subcategory` to be a primitive type in the JSON string but got " + data['subcategory']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }


}

RepoArticleSrcApiDtoArticleUpdateRequest.RequiredProperties = ["id"];

/**
 * @member {String} abstract
 */
RepoArticleSrcApiDtoArticleUpdateRequest.prototype['abstract'] = undefined;

/**
 * @member {String} category
 */
RepoArticleSrcApiDtoArticleUpdateRequest.prototype['category'] = undefined;

/**
 * @member {Number} id
 */
RepoArticleSrcApiDtoArticleUpdateRequest.prototype['id'] = undefined;

/**
 * @member {String} link
 */
RepoArticleSrcApiDtoArticleUpdateRequest.prototype['link'] = undefined;

/**
 * @member {String} subcategory
 */
RepoArticleSrcApiDtoArticleUpdateRequest.prototype['subcategory'] = undefined;

/**
 * @member {String} title
 */
RepoArticleSrcApiDtoArticleUpdateRequest.prototype['title'] = undefined;






export default RepoArticleSrcApiDtoArticleUpdateRequest;

