/**
 * article.newsbro.cc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest model module.
 * @module model/RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest
 * @version 1.3.2
 */
class RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest {
    /**
     * Constructs a new <code>RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest</code>.
     * @alias module:model/RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest
     * @param beginDate {String} 
     * @param endDate {String} 
     */
    constructor(beginDate, endDate) { 
        
        RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest.initialize(this, beginDate, endDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, beginDate, endDate) { 
        obj['begin_date'] = beginDate;
        obj['end_date'] = endDate;
    }

    /**
     * Constructs a <code>RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest} obj Optional instance to populate.
     * @return {module:model/RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest} The populated <code>RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest();

            if (data.hasOwnProperty('begin_date')) {
                obj['begin_date'] = ApiClient.convertToType(data['begin_date'], 'String');
            }
            if (data.hasOwnProperty('end_date')) {
                obj['end_date'] = ApiClient.convertToType(data['end_date'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['begin_date'] && !(typeof data['begin_date'] === 'string' || data['begin_date'] instanceof String)) {
            throw new Error("Expected the field `begin_date` to be a primitive type in the JSON string but got " + data['begin_date']);
        }
        // ensure the json data is a string
        if (data['end_date'] && !(typeof data['end_date'] === 'string' || data['end_date'] instanceof String)) {
            throw new Error("Expected the field `end_date` to be a primitive type in the JSON string but got " + data['end_date']);
        }

        return true;
    }


}

RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest.RequiredProperties = ["begin_date", "end_date"];

/**
 * @member {String} begin_date
 */
RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest.prototype['begin_date'] = undefined;

/**
 * @member {String} end_date
 */
RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest.prototype['end_date'] = undefined;






export default RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest;

