/**
 * Repo-Article
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RepoArticleSrcApiDtoRSSCreateRequest model module.
 * @module model/RepoArticleSrcApiDtoRSSCreateRequest
 * @version 1.0.0
 */
class RepoArticleSrcApiDtoRSSCreateRequest {
    /**
     * Constructs a new <code>RepoArticleSrcApiDtoRSSCreateRequest</code>.
     * @alias module:model/RepoArticleSrcApiDtoRSSCreateRequest
     * @param link {String} 
     * @param name {String} 
     */
    constructor(link, name) { 
        
        RepoArticleSrcApiDtoRSSCreateRequest.initialize(this, link, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, link, name, display_name) { 
        obj['link'] = link;
        obj['name'] = name;
        obj['display_name'] = display_name;
    }

    /**
     * Constructs a <code>RepoArticleSrcApiDtoRSSCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RepoArticleSrcApiDtoRSSCreateRequest} obj Optional instance to populate.
     * @return {module:model/RepoArticleSrcApiDtoRSSCreateRequest} The populated <code>RepoArticleSrcApiDtoRSSCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RepoArticleSrcApiDtoRSSCreateRequest();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('parent')) {
                obj['parent'] = ApiClient.convertToType(data['parent'], 'String');
            }
            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RepoArticleSrcApiDtoRSSCreateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RepoArticleSrcApiDtoRSSCreateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RepoArticleSrcApiDtoRSSCreateRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['link'] && !(typeof data['link'] === 'string' || data['link'] instanceof String)) {
            throw new Error("Expected the field `link` to be a primitive type in the JSON string but got " + data['link']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['parent'] && !(typeof data['parent'] === 'string' || data['parent'] instanceof String)) {
            throw new Error("Expected the field `parent` to be a primitive type in the JSON string but got " + data['parent']);
        }
        if (data['display_name'] && !(typeof data['display_name'] === 'string' || data['display_name'] instanceof String)) {
            throw new Error("Expected the field `display_name` to be a primitive type in the JSON string but got " + data['display_name']);
        }

        return true;
    }


}

RepoArticleSrcApiDtoRSSCreateRequest.RequiredProperties = ["link", "name"];

/**
 * @member {String} description
 */
RepoArticleSrcApiDtoRSSCreateRequest.prototype['description'] = undefined;

/**
 * @member {String} link
 */
RepoArticleSrcApiDtoRSSCreateRequest.prototype['link'] = undefined;

/**
 * @member {String} name
 */
RepoArticleSrcApiDtoRSSCreateRequest.prototype['name'] = undefined;

/**
 * @member {String} parent
 */
RepoArticleSrcApiDtoRSSCreateRequest.prototype['parent'] = undefined;

/**
 * @member {String} display_name
 */
RepoArticleSrcApiDtoRSSCreateRequest.prototype['display_name'] = undefined;

export default RepoArticleSrcApiDtoRSSCreateRequest;

