---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qdrant-secrets
  namespace: apps
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: qdrant-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: QDRANT__SERVICE__API_KEY
      remoteRef:
        key: qdrant
        property: api_key
