/**
 * account.newsbro.cc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RepoAccountSrcApiDtoUserResponse from './RepoAccountSrcApiDtoUserResponse';

/**
 * The RepoAccountSrcApiDtoLoginResponse model module.
 * @module model/RepoAccountSrcApiDtoLoginResponse
 * @version 1.3.2
 */
class RepoAccountSrcApiDtoLoginResponse {
    /**
     * Constructs a new <code>RepoAccountSrcApiDtoLoginResponse</code>.
     * @alias module:model/RepoAccountSrcApiDtoLoginResponse
     */
    constructor() { 
        
        RepoAccountSrcApiDtoLoginResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RepoAccountSrcApiDtoLoginResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RepoAccountSrcApiDtoLoginResponse} obj Optional instance to populate.
     * @return {module:model/RepoAccountSrcApiDtoLoginResponse} The populated <code>RepoAccountSrcApiDtoLoginResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RepoAccountSrcApiDtoLoginResponse();

            if (data.hasOwnProperty('access_token')) {
                obj['access_token'] = ApiClient.convertToType(data['access_token'], 'String');
            }
            if (data.hasOwnProperty('expires_in')) {
                obj['expires_in'] = ApiClient.convertToType(data['expires_in'], 'Number');
            }
            if (data.hasOwnProperty('refresh_token')) {
                obj['refresh_token'] = ApiClient.convertToType(data['refresh_token'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = RepoAccountSrcApiDtoUserResponse.constructFromObject(data['user']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RepoAccountSrcApiDtoLoginResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RepoAccountSrcApiDtoLoginResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['access_token'] && !(typeof data['access_token'] === 'string' || data['access_token'] instanceof String)) {
            throw new Error("Expected the field `access_token` to be a primitive type in the JSON string but got " + data['access_token']);
        }
        // ensure the json data is a string
        if (data['refresh_token'] && !(typeof data['refresh_token'] === 'string' || data['refresh_token'] instanceof String)) {
            throw new Error("Expected the field `refresh_token` to be a primitive type in the JSON string but got " + data['refresh_token']);
        }
        // validate the optional field `user`
        if (data['user']) { // data not null
          RepoAccountSrcApiDtoUserResponse.validateJSON(data['user']);
        }

        return true;
    }


}



/**
 * @member {String} access_token
 */
RepoAccountSrcApiDtoLoginResponse.prototype['access_token'] = undefined;

/**
 * @member {Number} expires_in
 */
RepoAccountSrcApiDtoLoginResponse.prototype['expires_in'] = undefined;

/**
 * @member {String} refresh_token
 */
RepoAccountSrcApiDtoLoginResponse.prototype['refresh_token'] = undefined;

/**
 * @member {module:model/RepoAccountSrcApiDtoUserResponse} user
 */
RepoAccountSrcApiDtoLoginResponse.prototype['user'] = undefined;






export default RepoAccountSrcApiDtoLoginResponse;

