/**
 * account.newsbro.cc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RepoAccountSrcApiDtoRegisterRequest model module.
 * @module model/RepoAccountSrcApiDtoRegisterRequest
 * @version 1.3.2
 */
class RepoAccountSrcApiDtoRegisterRequest {
    /**
     * Constructs a new <code>RepoAccountSrcApiDtoRegisterRequest</code>.
     * @alias module:model/RepoAccountSrcApiDtoRegisterRequest
     * @param email {String} 
     * @param password {String} 
     * @param username {String} 
     */
    constructor(email, password, username) { 
        
        RepoAccountSrcApiDtoRegisterRequest.initialize(this, email, password, username);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, password, username) { 
        obj['email'] = email;
        obj['password'] = password;
        obj['username'] = username;
    }

    /**
     * Constructs a <code>RepoAccountSrcApiDtoRegisterRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RepoAccountSrcApiDtoRegisterRequest} obj Optional instance to populate.
     * @return {module:model/RepoAccountSrcApiDtoRegisterRequest} The populated <code>RepoAccountSrcApiDtoRegisterRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RepoAccountSrcApiDtoRegisterRequest();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RepoAccountSrcApiDtoRegisterRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RepoAccountSrcApiDtoRegisterRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RepoAccountSrcApiDtoRegisterRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }

        return true;
    }


}

RepoAccountSrcApiDtoRegisterRequest.RequiredProperties = ["email", "password", "username"];

/**
 * @member {String} email
 */
RepoAccountSrcApiDtoRegisterRequest.prototype['email'] = undefined;

/**
 * @member {String} first_name
 */
RepoAccountSrcApiDtoRegisterRequest.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
RepoAccountSrcApiDtoRegisterRequest.prototype['last_name'] = undefined;

/**
 * @member {String} password
 */
RepoAccountSrcApiDtoRegisterRequest.prototype['password'] = undefined;

/**
 * @member {String} username
 */
RepoAccountSrcApiDtoRegisterRequest.prototype['username'] = undefined;






export default RepoAccountSrcApiDtoRegisterRequest;

