/**
 * account.newsbro.cc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RepoAccountSrcApiDtoUserResponse model module.
 * @module model/RepoAccountSrcApiDtoUserResponse
 * @version 1.3.2
 */
class RepoAccountSrcApiDtoUserResponse {
    /**
     * Constructs a new <code>RepoAccountSrcApiDtoUserResponse</code>.
     * @alias module:model/RepoAccountSrcApiDtoUserResponse
     */
    constructor() { 
        
        RepoAccountSrcApiDtoUserResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RepoAccountSrcApiDtoUserResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RepoAccountSrcApiDtoUserResponse} obj Optional instance to populate.
     * @return {module:model/RepoAccountSrcApiDtoUserResponse} The populated <code>RepoAccountSrcApiDtoUserResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RepoAccountSrcApiDtoUserResponse();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('is_active')) {
                obj['is_active'] = ApiClient.convertToType(data['is_active'], 'Boolean');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RepoAccountSrcApiDtoUserResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RepoAccountSrcApiDtoUserResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }

        return true;
    }


}



/**
 * @member {String} email
 */
RepoAccountSrcApiDtoUserResponse.prototype['email'] = undefined;

/**
 * @member {String} first_name
 */
RepoAccountSrcApiDtoUserResponse.prototype['first_name'] = undefined;

/**
 * @member {Number} id
 */
RepoAccountSrcApiDtoUserResponse.prototype['id'] = undefined;

/**
 * @member {Boolean} is_active
 */
RepoAccountSrcApiDtoUserResponse.prototype['is_active'] = undefined;

/**
 * @member {String} last_name
 */
RepoAccountSrcApiDtoUserResponse.prototype['last_name'] = undefined;

/**
 * @member {String} role
 */
RepoAccountSrcApiDtoUserResponse.prototype['role'] = undefined;

/**
 * @member {String} username
 */
RepoAccountSrcApiDtoUserResponse.prototype['username'] = undefined;






export default RepoAccountSrcApiDtoUserResponse;

