version: "3.8"

services:

  # KAFKA SERVICE
  redpanda:
    container_name: redpanda
    image: docker.redpanda.com/redpandadata/redpanda:v23.1.7
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
      - --memory 512M
    ports:
      - 9092:9092
      - 9644:9644
      - 29092:29092
    volumes:
      - redpanda:/var/lib/redpanda/data
    networks:
      - data-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  console:
    container_name: console
    image: docker.redpanda.com/redpandadata/console:v2.2.3
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
        connect:
          enabled: true
          clusters:
            - name: local-connect-cluster
              url: http://connect:8083
    ports:
      - 9002:8080
    depends_on:
      - redpanda
    networks:
      - data-net
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  # REDIS SERVICES
  redis-master:
    image: redis:alpine
    container_name: redis-master
    hostname: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./data/master:/data
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--repl-diskless-load",
        "on-empty-db",
        "--replica-announce-ip",
        "${HOST_IP}",
        "--replica-announce-port",
        "6379",
        "--protected-mode",
        "no"
      ]
    networks:
      redis-net:
        ipv4_address: 172.21.0.3

  redis-slave:
    image: redis:alpine
    container_name: redis-slave
    hostname: redis-slave
    depends_on:
      - redis-master
    ports:
      - "6380:6379"
    volumes:
      - ./data/slave1:/data
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--replicaof",
        "redis-master",
        "6379",
        "--repl-diskless-load",
        "on-empty-db",
        "--replica-announce-ip",
        "${HOST_IP}",
        "--replica-announce-port",
        "6380",
        "--protected-mode",
        "no"
      ]
    networks:
      redis-net:
        ipv4_address: 172.21.0.4

  redis-sentinel:
    image: redis:alpine
    container_name: redis-sentinel
    hostname: redis-sentinel
    depends_on:
      - redis-master
    ports:
      - "26379:26379"
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
        echo "sentinel monitor mymaster redis-master 6379 2" >> /etc/sentinel.conf &&
        echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
        echo "sentinel down-after-milliseconds mymaster 10000" >> /etc/sentinel.conf &&
        echo "sentinel failover-timeout mymaster 10000" >> /etc/sentinel.conf &&
        echo "sentinel parallel-syncs mymaster 1" >> /etc/sentinel.conf &&
        redis-sentinel /etc/sentinel.conf'
    networks:
      redis-data-net: {}
      redis-net:
        ipv4_address: 172.21.0.6

  redisinsight:
    image: redislabs/redisinsight:2.70
    container_name: redisinsight
    ports:
      - "5540:5540"
    networks:
      - redis-data-net

volumes:
  redpanda:

networks:
  data-net:
    driver: bridge
  redis-data-net:
  redis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
