---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: postgres
spec:
  interval: 10m0s
  chart:
    spec:
      chart: pgadmin4
      version: 1.50.0
      sourceRef:
        kind: HelmRepository
        name: helm-repo-pgadmin
        namespace: postgres
  values:
    replicaCount: 1

    image:
      registry: docker.io
      repository: dpage/pgadmin4
      tag: "9.8.0"
      pullPolicy: IfNotPresent
    imagePullSecrets: []

    annotations: {}
    revisionHistoryLimit: 10
    commonLabels: {}
    priorityClassName: ""

    service:
      type: ClusterIP
      clusterIP: ""
      loadBalancerIP: ""
      port: 80
      targetPort: 80
      portName: http
      annotations: {}

    serviceAccount:
      create: false
      annotations: {}
      name: ""
      automountServiceAccountToken: false

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1

    networkPolicy:
      enabled: true

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations: {}
      labels: {}
      hosts:
        - host: pgadmin.localhost
          paths:
            - path: /
              pathType: Prefix
      tls: []

    secretKeys:
      pgadminPasswordKey: password

    persistentVolume:
      enabled: true
      annotations: {}

      accessModes:
        - ReadWriteOnce

      size: 10Gi
      subPath: ""

    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 256Mi

    extraVolumes: []

    securityContext:
      runAsUser: 5050
      runAsGroup: 5050
      fsGroup: 5050

    containerSecurityContext:
      enabled: false
      allowPrivilegeEscalation: false

    startupProbe:
      failureThreshold: 30
      periodSeconds: 5