apiVersion: v1
kind: Secret
metadata:
  name: minio-s3-creds
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "minio"
  AWS_SECRET_ACCESS_KEY: "minio123"
  MLFLOW_S3_ENDPOINT_URL: "http://minio.minio.svc.cluster.local:8080"
  AWS_S3_ENDPOINT: "minio.minio.svc.cluster.local:8080"
  AWS_S3_USE_HTTPS: "0"     # using http
  AWS_S3_VERIFY_SSL: "0"