/**
 * Repo Feed Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RepoFeedSrcApiDtoArticle from './RepoFeedSrcApiDtoArticle';

/**
 * The RepoFeedSrcApiDtoFeedResponse model module.
 * @module model/RepoFeedSrcApiDtoFeedResponse
 * @version 1.0.0
 */
class RepoFeedSrcApiDtoFeedResponse {
    /**
     * Constructs a new <code>RepoFeedSrcApiDtoFeedResponse</code>.
     * @alias module:model/RepoFeedSrcApiDtoFeedResponse
     */
    constructor() { 
        
        RepoFeedSrcApiDtoFeedResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RepoFeedSrcApiDtoFeedResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RepoFeedSrcApiDtoFeedResponse} obj Optional instance to populate.
     * @return {module:model/RepoFeedSrcApiDtoFeedResponse} The populated <code>RepoFeedSrcApiDtoFeedResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RepoFeedSrcApiDtoFeedResponse();

            if (data.hasOwnProperty('articles')) {
                obj['articles'] = ApiClient.convertToType(data['articles'], [RepoFeedSrcApiDtoArticle]);
            }
            if (data.hasOwnProperty('model_name')) {
                obj['model_name'] = ApiClient.convertToType(data['model_name'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RepoFeedSrcApiDtoFeedResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RepoFeedSrcApiDtoFeedResponse</code>.
     */
    static validateJSON(data) {
        if (data['articles']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['articles'])) {
                throw new Error("Expected the field `articles` to be an array in the JSON data but got " + data['articles']);
            }
            // validate the optional field `articles` (array)
            for (const item of data['articles']) {
                RepoFeedSrcApiDtoArticle.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['model_name'] && !(typeof data['model_name'] === 'string' || data['model_name'] instanceof String)) {
            throw new Error("Expected the field `model_name` to be a primitive type in the JSON string but got " + data['model_name']);
        }
        // ensure the json data is a string
        if (data['updated_at'] && !(typeof data['updated_at'] === 'string' || data['updated_at'] instanceof String)) {
            throw new Error("Expected the field `updated_at` to be a primitive type in the JSON string but got " + data['updated_at']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/RepoFeedSrcApiDtoArticle>} articles
 */
RepoFeedSrcApiDtoFeedResponse.prototype['articles'] = undefined;

/**
 * @member {String} model_name
 */
RepoFeedSrcApiDtoFeedResponse.prototype['model_name'] = undefined;

/**
 * @member {String} updated_at
 */
RepoFeedSrcApiDtoFeedResponse.prototype['updated_at'] = undefined;

/**
 * @member {Number} user_id
 */
RepoFeedSrcApiDtoFeedResponse.prototype['user_id'] = undefined;






export default RepoFeedSrcApiDtoFeedResponse;

