/**
 * Repo Feed Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import RepoFeedSrcApiDtoFeedResponse from '../model/RepoFeedSrcApiDtoFeedResponse';

/**
* Feed service.
* @module api/FeedApi
* @version 1.0.0
*/
export default class FeedApi {

  /**
  * Constructs a new FeedApi. 
  * @alias module:api/FeedApi
  * @class
  * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
  * default to {@link module:ApiClient#instance} if unspecified.
  */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }


  /**
   * Callback function to receive the result of the feedGet operation.
   * @callback module:api/FeedApi~feedGetCallback
   * @param {String} error Error message, if any.
   * @param {module:model/RepoFeedSrcApiDtoFeedResponse} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Get user feed
   * Get the feed of the authenticated user
   * @param {Object} opts Optional parameters
   * @param {String} [model] Model name (optional, uses default if not specified)
   * @param {module:api/FeedApi~feedGetCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link module:model/RepoFeedSrcApiDtoFeedResponse}
   */
  feedGet(opts, callback) {
    opts = opts || {};
    let postBody = null;

    let pathParams = {
    };
    let queryParams = {
      'model': opts['model']
    };
    let headerParams = {
    };
    let formParams = {
    };

    let authNames = [];
    let contentTypes = [];
    let accepts = ['application/json'];
    let returnType = RepoFeedSrcApiDtoFeedResponse;
    return this.apiClient.callApi(
      '/api/v1/feed', 'GET',
      pathParams, queryParams, headerParams, formParams, postBody,
      authNames, contentTypes, accepts, returnType, null, callback
    );
  }

  /**
* Remove article from feed
* Remove a specific article from the authenticated user's feed
* @param {Number} id Article ID
* @param {module:api/FeedApi~feedIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
*/
  feedIdDelete(id, callback) {
    let postBody = null;
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error("Missing the required parameter 'id' when calling feedIdDelete");
    }

    let pathParams = {
      'id': id
    };
    let queryParams = {
    };
    let headerParams = {
    };
    let formParams = {
    };

    let authNames = [];
    let contentTypes = [];
    let accepts = ['application/json'];
    let returnType = null;
    return this.apiClient.callApi(
      '/api/v1/feed/{id}', 'DELETE',
      pathParams, queryParams, headerParams, formParams, postBody,
      authNames, contentTypes, accepts, returnType, null, callback
    );
  }

  /**
   * Callback function to receive the result of the feedModelsGet operation.
   * @callback module:api/FeedApi~feedModelsGetCallback
   * @param {String} error Error message, if any.
   * @param {Array.<String>} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Get user feed models
   * Get the models available for user feed
   * @param {module:api/FeedApi~feedModelsGetCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link Array.<String>}
   */
  feedModelsGet(callback) {
    let postBody = null;

    let pathParams = {
    };
    let queryParams = {
    };
    let headerParams = {
    };
    let formParams = {
    };

    let authNames = [];
    let contentTypes = [];
    let accepts = ['application/json'];
    let returnType = ['String'];
    return this.apiClient.callApi(
      '/api/v1/feed/models', 'GET',
      pathParams, queryParams, headerParams, formParams, postBody,
      authNames, contentTypes, accepts, returnType, null, callback
    );
  }


}
