/**
 * Repo Feed Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RepoFeedServiceApi);
  }
}(this, function(expect, RepoFeedServiceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RepoFeedServiceApi.RepoFeedSrcApiDtoArticle();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RepoFeedSrcApiDtoArticle', function() {
    it('should create an instance of RepoFeedSrcApiDtoArticle', function() {
      // uncomment below and update the code to test RepoFeedSrcApiDtoArticle
      //var instance = new RepoFeedServiceApi.RepoFeedSrcApiDtoArticle();
      //expect(instance).to.be.a(RepoFeedServiceApi.RepoFeedSrcApiDtoArticle);
    });

    it('should have the property _abstract (base name: "abstract")', function() {
      // uncomment below and update the code to test the property _abstract
      //var instance = new RepoFeedServiceApi.RepoFeedSrcApiDtoArticle();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new RepoFeedServiceApi.RepoFeedSrcApiDtoArticle();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new RepoFeedServiceApi.RepoFeedSrcApiDtoArticle();
      //expect(instance).to.be();
    });

    it('should have the property link (base name: "link")', function() {
      // uncomment below and update the code to test the property link
      //var instance = new RepoFeedServiceApi.RepoFeedSrcApiDtoArticle();
      //expect(instance).to.be();
    });

    it('should have the property publishedAt (base name: "published_at")', function() {
      // uncomment below and update the code to test the property publishedAt
      //var instance = new RepoFeedServiceApi.RepoFeedSrcApiDtoArticle();
      //expect(instance).to.be();
    });

    it('should have the property rssLink (base name: "rss_link")', function() {
      // uncomment below and update the code to test the property rssLink
      //var instance = new RepoFeedServiceApi.RepoFeedSrcApiDtoArticle();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "score")', function() {
      // uncomment below and update the code to test the property score
      //var instance = new RepoFeedServiceApi.RepoFeedSrcApiDtoArticle();
      //expect(instance).to.be();
    });

    it('should have the property subcategory (base name: "subcategory")', function() {
      // uncomment below and update the code to test the property subcategory
      //var instance = new RepoFeedServiceApi.RepoFeedSrcApiDtoArticle();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new RepoFeedServiceApi.RepoFeedSrcApiDtoArticle();
      //expect(instance).to.be();
    });

  });

}));
