apiVersion: v1
kind: ConfigMap
metadata:
  name: srvc-scrapping-config
  namespace: apps
data:
  # Application
  GIN_MODE: release
  PORT: "8080"
  ENVIRONMENT: prod
  # Postgres
  DATABASE_NAME: srvc-scrapping
  # Kafka
  KAFKA_GROUP_ID: srvc-scrapping-group
