/**
 * article.newsbro.cc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import RepoArticleSrcApiDtoArticleCreateRequest from './model/RepoArticleSrcApiDtoArticleCreateRequest';
import RepoArticleSrcApiDtoArticleResponse from './model/RepoArticleSrcApiDtoArticleResponse';
import RepoArticleSrcApiDtoArticleTriggerIngestionRequest from './model/RepoArticleSrcApiDtoArticleTriggerIngestionRequest';
import RepoArticleSrcApiDtoArticleUpdateRequest from './model/RepoArticleSrcApiDtoArticleUpdateRequest';
import RepoArticleSrcApiDtoErrorResponse from './model/RepoArticleSrcApiDtoErrorResponse';
import RepoArticleSrcApiDtoFeedbackRequest from './model/RepoArticleSrcApiDtoFeedbackRequest';
import RepoArticleSrcApiDtoFeedbackResponse from './model/RepoArticleSrcApiDtoFeedbackResponse';
import RepoArticleSrcApiDtoFeedbackStatsResponse from './model/RepoArticleSrcApiDtoFeedbackStatsResponse';
import RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest from './model/RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest';
import ArticlesApi from './api/ArticlesApi';
import FeedbackApi from './api/FeedbackApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ArticleNewsbroCc = require('index'); // See note below*.
* var xxxSvc = new ArticleNewsbroCc.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ArticleNewsbroCc.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ArticleNewsbroCc.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ArticleNewsbroCc.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.3.2
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The RepoArticleSrcApiDtoArticleCreateRequest model constructor.
     * @property {module:model/RepoArticleSrcApiDtoArticleCreateRequest}
     */
    RepoArticleSrcApiDtoArticleCreateRequest,

    /**
     * The RepoArticleSrcApiDtoArticleResponse model constructor.
     * @property {module:model/RepoArticleSrcApiDtoArticleResponse}
     */
    RepoArticleSrcApiDtoArticleResponse,

    /**
     * The RepoArticleSrcApiDtoArticleTriggerIngestionRequest model constructor.
     * @property {module:model/RepoArticleSrcApiDtoArticleTriggerIngestionRequest}
     */
    RepoArticleSrcApiDtoArticleTriggerIngestionRequest,

    /**
     * The RepoArticleSrcApiDtoArticleUpdateRequest model constructor.
     * @property {module:model/RepoArticleSrcApiDtoArticleUpdateRequest}
     */
    RepoArticleSrcApiDtoArticleUpdateRequest,

    /**
     * The RepoArticleSrcApiDtoErrorResponse model constructor.
     * @property {module:model/RepoArticleSrcApiDtoErrorResponse}
     */
    RepoArticleSrcApiDtoErrorResponse,

    /**
     * The RepoArticleSrcApiDtoFeedbackRequest model constructor.
     * @property {module:model/RepoArticleSrcApiDtoFeedbackRequest}
     */
    RepoArticleSrcApiDtoFeedbackRequest,

    /**
     * The RepoArticleSrcApiDtoFeedbackResponse model constructor.
     * @property {module:model/RepoArticleSrcApiDtoFeedbackResponse}
     */
    RepoArticleSrcApiDtoFeedbackResponse,

    /**
     * The RepoArticleSrcApiDtoFeedbackStatsResponse model constructor.
     * @property {module:model/RepoArticleSrcApiDtoFeedbackStatsResponse}
     */
    RepoArticleSrcApiDtoFeedbackStatsResponse,

    /**
     * The RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest model constructor.
     * @property {module:model/RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest}
     */
    RepoArticleSrcApiDtoFeedbackTriggerIngestionRequest,

    /**
    * The ArticlesApi service constructor.
    * @property {module:api/ArticlesApi}
    */
    ArticlesApi,

    /**
    * The FeedbackApi service constructor.
    * @property {module:api/FeedbackApi}
    */
    FeedbackApi
};
