apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mlflow
  namespace: mlflow
spec:
  interval: 10m0s
  chart:
    spec:
      chart: mlflow
      version: 1.7.0
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: mlflow
  values:
    log:
      level: info
      enabled: true

    ingress:
      enabled: true
      className: "traefik"
      hosts:
        - host: mlflow.localhost
          paths:
            - path: /
              pathType: Prefix

    extraVolumes:
      - name: mlflow-volume
        persistentVolumeClaim:
          claimName: mlflow-pvc

    extraVolumeMounts:
      - name: mlflow-volume
        mountPath: /tmp

    service:
      name: http
      port: 5000
      type: ClusterIP
      enabled: true
      containerPort: 5000
      containerPortName: mlflow

    strategy:
      type: RollingUpdate

    extraArgs:
      workers: "4"

    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 1Gi

    telemetry:
      enabled: true

    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 70

    artifactRoot:
      proxiedArtifactStorage: true
      s3:
        bucket: "mlflow"
        enabled: true
        existingSecret:
          name: "mlflow-s3-secret"
          keyOfAccessKeyId: "username"
          keyOfSecretAccessKey: "password"

    backendStore:
      postgres:
        enabled: true
        host: "postgres-cluster-rw.postgres.svc.cluster.local"
        port: 5432
        database: "mlflow"
        driver: "psycopg2"
      databaseMigration: true
      databaseConnectionCheck: true
      existingDatabaseSecret:
        name: "mlflow-db-secret"
        usernameKey: "username"
        passwordKey: "password"

    extraEnvVars:
      # S3 Configuration
      AWS_DEFAULT_REGION: "us-east-1"
      MLFLOW_S3_IGNORE_TLS: true
      MLFLOW_S3_ENDPOINT_URL: "http://minio-new-svc.minio.svc.cluster.local:9000"

      # Database Connection Pooling
      MLFLOW_SQLALCHEMYSTORE_POOL_SIZE: "10"  # SQLAlchemy connection pool size
      MLFLOW_SQLALCHEMYSTORE_MAX_OVERFLOW: "20"  # SQLAlchemy max overflow connections
      MLFLOW_SQLALCHEMYSTORE_POOL_RECYCLE: "3600"  # SQLAlchemy pool recycle time

      # Logging and Monitoring
      MLFLOW_LOGGING_LEVEL: "INFO"  # MLflow logging level
      MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING: "true"  # Enable system metrics logging
      MLFLOW_SYSTEM_METRICS_SAMPLING_INTERVAL: "1.0"  # System metrics sampling interval

    replicaCount: 1

    livenessProbe:
      periodSeconds: 30
      timeoutSeconds: 3
      failureThreshold: 5
      initialDelaySeconds: 10

    readinessProbe:
      periodSeconds: 30
      timeoutSeconds: 3
      failureThreshold: 5
      initialDelaySeconds: 10

    serviceAccount:
      name: ""
      create: true
      automount: true

    serviceMonitor:
      labels:
        release: prometheus
      enabled: false
      timeout: 10s
      interval: 30s
      namespace: monitoring
      telemetryPath: /metrics
      useServicePort: false

    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false

    podSecurityContext:
      fsGroup: 2000
      runAsUser: 1000
      runAsGroup: 3000
      fsGroupChangePolicy: OnRootMismatch

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              version: v1
              name: mlflow
            patch: |
              - op: replace
                path: /spec/template/spec/containers/0/command
                value:
                  - /mlflow/.venv/bin/mlflow
